# Generated by Django 3.0.5 on 2021-01-16 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('ภาคเหนือ', 'North'), ('ภาคใต้', 'South'), ('ภาคกลาง', 'Central'), ('ภาคตะวันออก', 'East'), ('ภาคตะวันออกเฉียงเหนือ', 'NorthEast'), ('ภาคตะวันตก', 'West')], default='Central', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Airforce', 'Airforce'), ('Police', 'Police')], default='Airforce', max_length=10)),
                ('birthDay', models.DateField(null=True)),
                ('officeName', models.CharField(max_length=200)),
                ('mobilePhone', models.CharField(max_length=50)),
                ('officePhone', models.CharField(max_length=50, null=True)),
                ('business', models.TextField(blank=True)),
                ('hobby', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('shirtSize', models.CharField(max_length=50, null=True)),
                ('wifeShirtSize', models.CharField(max_length=50, null=True)),
                ('kidShirtSize', models.CharField(max_length=50, null=True)),
                ('socialContact', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('isAdmin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactData.TProvince')),
            ],
        ),
    ]
